baseURL = 'https://solo-code-tw.github.io/'
languageCode = 'en-us'
title = 'Solo Code Blog'
theme = ["github.com/adityatelange/hugo-PaperMod"]

[params]
    env = "production"
[module]
  [[module.imports]]
    path = "github.com/adityatelange/hugo-PaperMod"
# test
